"""Add projects and badges

Revision ID: 25a36669071e
Revises: 5eb1b36f4ffe
Create Date: 2023-07-06 07:47:55.104059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25a36669071e'
down_revision = '5eb1b36f4ffe'
branch_labels = None
depends_on = None


def upgrade() -> None:

    op.create_table('badges',
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name='badges_pkey')
    )

    op.create_table('projects',
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('badge_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('debt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('indexing_done', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analysing_done', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.uid'], name='projects_badge_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], name='projects_user_id_fkey'),
    sa.PrimaryKeyConstraint('uid', name='projects_pkey')
    )

    op.create_foreign_key('fk_projects_user_id_users', 'projects', 'users', ['user_id'], ['uid'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects', cascade=True)
    op.drop_table('badges', cascade=True)
    # ### end Alembic commands ###
